analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
