name: Documentation
description: Improve the documentation so all collaborators have a common understanding
title: "docs: "
labels: [documentation]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what documentation you are looking to add or improve.
      placeholder: "Provide a description of the documentation changes."
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: The list of requirements that need to be met in order to consider the ticket to be completed. Please be as explicit as possible.
      value: |
        - [ ] No functional changes to the code.
        - [ ] All CI/CD checks are passing.
        - [ ] There is no drop in the test coverage percentage.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, including links/screenshots/video recordings/etc about the problem here.
      placeholder: "Provide context here."
