name: Performance Update
description: A code change that improves performance
title: "perf: "
labels: [performance]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe what code needs to be changed and what the performance impact is going to be. Bonus point's if you can tie this directly to user experience.
      placeholder: " Provide a description of the performance update."
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: The list of requirements that need to be met in order to consider the ticket to be completed. Please be as explicit as possible.
      value: |
        - [ ] All CI/CD checks are passing.
        - [ ] There is no drop in the test coverage percentage.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, including links/screenshots/video recordings/etc about the problem here.
      placeholder: "Provide context here."
