name: Revert
description: Revert a previous commit
title: "revert: "
labels: [revert]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a link to a PR/Commit that you are looking to revert and why.
      placeholder: "Provide a description of and link to the commit that needs to be reverted."
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: The list of requirements that need to be met in order to consider the ticket to be completed. Please be as explicit as possible.
      value: |
        - [ ] Change has been reverted.
        - [ ] No change in unit/widget test coverage has happened.
        - [ ] A new ticket is created for any follow on work that needs to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, including links/screenshots/video recordings/etc about the problem here.
      placeholder: "Provide context here."
