name: atmos_cli_e2e
description: End to End tests for package:atmos_cli
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  atmos_cli:
    path: ../
  mason: ^0.1.0-dev.50
  mocktail: ^1.0.0
  path: ^1.8.0
  pub_updater: ^0.5.0
  test: ^1.25.0
  universal_io: ^2.0.4
  very_good_analysis: ^6.0.0
