name: very_good_cli_e2e
description: End to End tests for package:very_good_cli
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  mason: ^0.1.0-dev.50
  mocktail: ^1.0.0
  path: ^1.8.0
  pub_updater: ^0.4.0
  test: ^1.25.0
  universal_io: ^2.0.4
  very_good_analysis: ^5.1.0
  very_good_cli:
    path: ../
