name: very_good_cli_e2e
description: End to End tests for package:very_good_cli
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  mason: ^0.1.0-dev.49
  mocktail: ^0.3.0
  path: ^1.8.0
  pub_updater: ^0.2.4
  test: ^1.19.2
  universal_io: ^2.0.4
  usage: ^4.0.2
  very_good_analysis: ^4.0.0
  very_good_cli:
    path: ../
