name: very_good_core
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
