name: check_links

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Runs every Monday at 08:00 UTC
    - cron: "0 8 * * 1"

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🔗 Check Links
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-path 'lib/src/commands/create/templates'
            --exclude-path 'site'
            '**/*.md'
            '**/*.dart'
          fail: true
