name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: "**/*.md"
      modified_files_only: false

  pana:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
