name: very_good_cli

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/very_good_cli.yaml"
      - "bin/**"
      - "bricks/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/very_good_cli.yaml"
      - "bin/**"
      - "bricks/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      runs_on: ${{ matrix.os }}
      flutter_version: "3.44.x"
      coverage_excludes: "**/*.{gen,g}.dart"
      concurrency: 1
      run_skipped: true
      run_bloc_lint: false
      test_optimization: false

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      pana_version: 0.22.22
